""" 
Generated by Claude Opus 4.7 To help with debugging
"""

import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np
from matplotlib.patches import Ellipse


class SignaturePlotter:
    def __init__(self, xlim=(-5, 5), ylim=(-5, 5), n_std=2.0):
        """
        Live plot of signatures from multiple SignatureQueue sources.

        :param xlim, ylim: fixed axis limits (m). Set None for autoscale.
        :param n_std: covariance ellipse size in standard deviations.
        """
        self._xlim = xlim
        self._ylim = ylim
        self._n_std = n_std

        # stable colour per queue name, assigned on first sight
        self._colours = {}
        self._cmap = cm.get_cmap('tab10')
        self._next_colour = 0

        plt.ion()
        self._fig, self._ax = plt.subplots(1, 1, figsize=(8, 8))
        self._fig.suptitle('Signature Queues')

    def _colour_for(self, name):
        if name not in self._colours:
            self._colours[name] = self._cmap(self._next_colour % 10)
            self._next_colour += 1
        return self._colours[name]

    def _draw_covariance(self, x, y, flat_cov, colour):
        """Draw an n_std covariance ellipse from a flat [xx, xy, yx, yy] list."""
        cov = np.array(flat_cov, dtype=float).reshape(2, 2)

        # eigen-decomposition gives ellipse axes (eigenvectors) and
        # their lengths (sqrt of eigenvalues)
        eigvals, eigvecs = np.linalg.eigh(cov)
        eigvals = np.clip(eigvals, 0.0, None)  # guard tiny negatives

        # angle of the major axis
        angle = np.degrees(np.arctan2(eigvecs[1, 0], eigvecs[0, 0]))

        width, height = 2.0 * self._n_std * np.sqrt(eigvals)

        ell = Ellipse(
            (x, y), width=width, height=height, angle=angle,
            facecolor=colour, edgecolor=colour, alpha=0.2, lw=1.0
        )
        self._ax.add_patch(ell)

    def update_plots(self, queues):
        """
        Redraw all signatures.

        :param queues: list of SignatureQueue objects.
        """
        self._ax.cla()
        self._ax.set_title('Tracked Signatures')
        self._ax.set_xlabel('x (m)')
        self._ax.set_ylabel('y (m)')
        self._ax.set_aspect('equal')
        self._ax.grid(True)

        if self._xlim:
            self._ax.set_xlim(self._xlim)
        if self._ylim:
            self._ax.set_ylim(self._ylim)

        # robot origin for reference
        self._ax.scatter(0, 0, s=120, marker='+', c='black', zorder=5)

        for q in queues:
            colour = self._colour_for(q.name)

            xs, ys = [], []
            for s in q.queue:
                xs.append(s.x)
                ys.append(s.y)
                if s.covariance is not None:
                    self._draw_covariance(s.x, s.y, s.covariance, colour)

            # one scatter call per queue so the legend has one entry per source
            self._ax.scatter(
                xs, ys, s=40, color=colour,
                label=f'{q.name} ({len(q.queue)})', zorder=3
            )

        self._ax.legend(loc='upper right', fontsize=8)

        self._fig.canvas.draw()
        self._fig.canvas.flush_events()