launch_settings:
  radar_modules:
    - identifier: 0
      interface: /dev/ttyAMA0
      parent_frame: base_link
      translation_x: 0.046
      translation_y: 0.075
      translation_z: 0.134
      roll: 0.00
      pitch: -0.785398
      yaw: 0.00
    - identifier: 1
      interface: /dev/ttyAMA1
      parent_frame: base_link
      translation_x: 0.046
      translation_y: 0.0
      translation_z: 0.134
      roll: 0.00
      pitch: -0.785398
      yaw: 0.00
    - identifier: 2
      interface: /dev/ttyAMA2
      parent_frame: base_link
      translation_x: 0.046
      translation_y: -0.075
      translation_z: 0.134
      roll: 0.00
      pitch: -0.785398
      yaw: 0.00



