launch_settings:
  radar_modules:
    - identifier: 99
      interface: /dev/ttyAMA0
      parent_frame: base_link
      translation_x: 0.092
      translation_y: 0.092
      translation_z: 0.092
      roll: 0.05
      pitch: 0.05
      yaw: 0.05



